import Head from 'next/head';
import Instagram from '../components/Instagram';
import Slider from '../components/Slider';
import Hero from '../components/Hero';
import { SliderData } from '../components/SliderData';
import Navbar from '../components/Navbar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>My album</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero heading='My Album' message='This is a collection of photoes that are special to me' />
      <Navbar />
      <Slider slides={SliderData} />
      <Instagram />
    </div>
  );
}
